import "./globals.css";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
// import { createContext } from "react";
// import useGenres from "@/hooks/useGenres";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//  export const context = createContext(useGenres)

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
